### ISSUE TITLE
install failure  object 'do' not found whilst loading namespace 'rcdk'

### ISSUE THREAD

**Issue by trljcl** [CDK-R/cdkr#102]
Hi, I've moved to a new linux box and am trying to reinstall rcdk using devtools (I need >= 3.4.8 for correct handing of isotope designations in element lists).  I did this successfully ~ a year ago on R3.5.0  and am repeating the same procedure now on the new box under r3.6.2 (after first checking all dependencies are installed).  rcdklibs installs fine, but rcdk does not - any advice much appreciated!

library("devtools")
> install_github("https://github.com/CDK-R/cdkr", subdir="rcdk")
Downloading GitHub repo CDK-R/cdkr@master
v  checking for file '/tmp/RtmpkOtxb2/remotes29b5186eac66/CDK-R-cdkr-049850a/rcdk/DESCRIPTION' (505ms)
-  preparing 'rcdk':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'rcdk_3.4.9.2.tar.gz'
   Warning: invalid uid value replaced by that for user 'nobody'

* installing *source* package 'rcdk' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'rcdk':
 object 'do' not found whilst loading namespace 'rcdk'
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/shared/storage/biology/rsrch/tf-PAB/lab/trl1/bin_research1/lib/R/library/rcdk'
Error: Failed to install 'rcdk' from GitHub:
 
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /shared/storage/biology/rsrch/tf-PAB/lab/trl1/bin_research1/lib/R/lib/libRblas.so
LAPACK: /shared/storage/biology/rsrch/tf-PAB/lab/trl1/bin_research1/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB       LC_NUMERIC=C         LC_TIME=en_GB
 [4] LC_COLLATE=en_GB     LC_MONETARY=en_GB    LC_MESSAGES=en_GB
 [7] LC_PAPER=en_GB       LC_NAME=C            LC_ADDRESS=C
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_GB LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2
>

**Comment by zachcp** [comment]
Sorry, @trljcl , this should be fixed in #101. In the meantime you can try below:

```
# I can replicate your bug
install_github("https://github.com/CDK-R/cdkr", subdir="rcdk")

# this should work
install_github("https://github.com/zachcp/cdkr", subdir="rcdk", ref="docfixes")
```

**Comment by zachcp** [comment]
#101 is merged. closing. if the issue persists, feel free to reopen

**Comment by zachcp** [comment]
@trljcl can you see if this is still an issue and close if its resolved.
