### ISSUE TITLE
cdk implementation in R::depict

### ISSUE THREAD

**Issue by dgcovell** [CDK-R/cdkr#137]
I have successfully used the R::depict uti;lity for highlighting 2D structures. In this process, I have encountered
a problem when the highlighted structure is an imidazole. Reading blogs indicates that the tautomer status 
can be a problem. However, I have not found a SMILES representation that will highlight any imidazole in a structure.
I am sure the answer is buried well above my skill set, but since R::depict used cdk, someone might have the answer.
If anyone can use R::depict to highlight the imizadole in the
structure below please chime in. 
The R::depict calls are:

library(depict)
library(magrittr)
library(grid)

  > tmp_smi
[1] "CC(n1c(C)ncc1c1ccnc(n1)Nc1ccc(cc1)S(=O)(=O)C)C"
> tmp_label
[1] "CMGC:CDC2:6gu3:A:FB8"
   pen <- parse_smiles(paste(tmp_smi, tmp_label,sep=" "))
   atms <- pen$atoms()
   bnds <- pen$bonds()
   tmp_frag <- 'c1cnc[nH]1'  #1H-imidazole
   cav <- parse.smiles(tmp_frag)
   lactam <- match_smarts(tmp_frag, pen)
      depiction() %>%
             highlight_atoms(atms, color$LIGHT_GRAY) %>%
             highlight_atoms(bnds, color$LIGHT_GRAY) %>%
             highlight_atoms(lactam, color$GREEN) %>%
             set_size(1400, 1400) %>%
             set_zoom(4) %>%
             outerglow() %>%
#             add_title() %>%
             depict(pen) %>%
             get_image() %>%
             grid::grid.raster()

Thanks

**Comment by zachcp** [comment]
@dgcovell  I am also not an expert on SMARTS matching (he CDK class of interest is [here](http://cdk.github.io/cdk/2.8/docs/api/org/openscience/cdk/smarts/SmartsPattern.html) ) . But maybe the code bleo is helpful as a termporary workaround

```r
library(depict)

try_highlighting <- function(pattern) {
  mol       <- parse_smiles(paste("CC(n1c(C)ncc1c1ccnc(n1)Nc1ccc(cc1)S(=O)(=O)C)C", 
                                  "CMGC:CDC2:6gu3:A:FB8", sep=" "))
  
  # imid      <- 'c1cnc[nH]1'  #1H-imidazole
  imid_highlight <- match_smarts(pattern, mol)
  
  color <- J("java.awt.Color")
  
  depiction() |>
    highlight_atoms(imid_highlight, color$GREEN) |>
    set_size(1400, 1400) |>
    set_zoom(4) |>
    outerglow() |>
    add_title() |>
    depict(mol) |>
    get_image() |>
    grid::grid.raster()
  
  
  
}

# this one does not highlight
try_highlighting('c1cnc[nH]1')

# this looks right
try_highlighting('c1cncn1')
```

![image](https://user-images.githubusercontent.com/1260667/200200382-316601ef-7359-4e28-ad22-0437431ef77a.png)

**Comment by dgcovell** [comment]
Zach,  Thanks. This works, however I need to also highlight
 "n1cccnc1Nc2ccccc2" in a different color and add the outerglow.
My attempts to modify your try_highlighting function have failed.

Again, you help is most appreciated.

David

**Comment by zachcp** [comment]
```r
library(depict)



mol       <- parse_smiles(paste("CC(n1c(C)ncc1c1ccnc(n1)Nc1ccc(cc1)S(=O)(=O)C)C", 
                                "CMGC:CDC2:6gu3:A:FB8", sep=" "))

# imid      <- 'c1cnc[nH]1'  #1H-imidazole
highlight_imid <- match_smarts("c1cncn1", mol)
highlight_2    <- match_smarts("n1cccnc1Nc2ccccc2", mol)

color <- J("java.awt.Color")

depiction() |>
  highlight_atoms(highlight_imid, color$GREEN) |>
  highlight_atoms(highlight_2, color$RED) |>
  set_size(1400, 1400) |>
  set_zoom(4) |>
  outerglow() |>
  add_title() |>
  depict(mol) |>
  get_image() |>
  grid::grid.raster()

```

<img width="433" alt="image" src="https://user-images.githubusercontent.com/1260667/200662687-d918800e-1710-472a-8bf2-bb9d6c7ee17d.png">
