### ISSUE TITLE
Remove atoms with CDK

### ISSUE THREAD

**Issue by xdomingoal** [CDK-R/cdkr#141]
How can you remove a specific atom from a molecule (IAtomContainer) using CDK in R?

**Comment by zachcp** [comment]
Hi, here is an example.

```r

# devtools::install_github("CDK-R/depict")


library(rcdk)
library(depict)


mol <- depict::parse_smiles("C1CCCCC1")

depiction() %>%
  depict(mol) %>%
  get_image() %>%
  grid::grid.raster()

# use rJava `as.list` method to view the Java iterator as a list
list_of_atoms <- as.list(mol$atoms())


# delete the atom of interest
mol$removeAtom(list_of_atoms[[1]])


depiction() %>%
  depict(mol) %>%
  get_image() %>%
  grid::grid.raster()

```

<img width="207" alt="Screen Shot 2023-03-21 at 7 20 20 AM" src="https://user-images.githubusercontent.com/1260667/226591191-bba78d0d-309d-4a9c-bd26-458c798c1746.png">
<img width="212" alt="Screen Shot 2023-03-21 at 7 20 52 AM" src="https://user-images.githubusercontent.com/1260667/226591301-6b9a295c-1345-44ca-9aff-12186d31d68d.png">
