### ISSUE TITLE
Update to CDK 2.9

### ISSUE THREAD

**Issue by zachcp** [CDK-R/cdkr#149]
- [x] [egonw update request](https://github.com/cdk/nwo-openscience-2024/issues/14)
- [ ] Implement [Release note figures  as vignettes](https://github.com/cdk/cdk/releases).
    - [x] [2.9 Release Notes](https://github.com/cdk/cdk/releases/tag/cdk-2.9)
    - [ ] [2.8 Release Notes](https://github.com/cdk/cdk/releases/tag/cdk-2.8)
    - [ ] [2.5 Release Notes](https://github.com/cdk/cdk/wiki/2.5-Release-Notes)
    - [ ] [2.4 Release Notes](https://github.com/cdk/cdk/wiki/2.3-Release-Notes)
    - [ ] [2.2 Release Notes](https://github.com/cdk/cdk/wiki/2.2-Release-Notes)
- [x] Take a stab at the open issues
- [ ] Add auto close of stale issues.
- [x] Create an Icon
- [x] Get cdklibs 2.9 to CRAN.

**Comment by egonw** [comment]
@zachcp, this has been completed, right?
