### ISSUE TITLE
Error in molecule visualization after rcdk 3.4.5 update

### ISSUE THREAD

**Issue by Tebatu** [CDK-R/cdkr#61]
Hi, 
I updated rcdk today to the newest version and the functionality of `view.molecule.2d()` broke down. I tried to execute the chunk from the vignette and get the following error:

```
library(rcdk)
Loading required package: rcdklibs
Loading required package: rJava
smiles <- c('CCC', 'CCN', 'CCN(C)(C)',
 'c1ccccc1Cc1ccccc1','C1CCC1CC(CN(C)(C))CC(=O)CC')
mols <- parse.smiles(smiles)
view.molecule.2d(mols[[1]])
Error in .jnew("org/guha/rcdk/view/ViewMolecule2D", molecule, as.integer(width),  : 
  java.lang.NoSuchMethodError: <init>

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rcdk_3.4.5   rcdklibs_2.0 rJava_0.9-9 

loaded via a namespace (and not attached):
[1] compiler_3.4.3    parallel_3.4.3    fingerprint_3.5.6 tools_3.4.3       iterators_1.0.9  
[6] itertools_0.1-3   png_0.1-7    
```
My Java build is `(build 1.8.0_151-b12)`

**Comment by schymane** [comment]
Did you try looking at the examples in the function documentation? The functionality upgraded a while back and it's not compatible with older rcdk versions (but the new features are cool!), the examples were updated (I never looked at the vignette to see there)



On Fri, Dec 15, 2017 at 4:29 PM +0100, "Tebatu" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I updated rcdk today to the newest version and the functionality of view.molecule.2d() broke down. I tried to execute the chunk from the vignette and get the following error:

library(rcdk)
Loading required package: rcdklibs
Loading required package: rJava
smiles <- c('CCC', 'CCN', 'CCN(C)(C)',
 'c1ccccc1Cc1ccccc1','C1CCC1CC(CN(C)(C))CC(=O)CC')
mols <- parse.smiles(smiles)
view.molecule.2d(mols[[1]])
Error in .jnew("org/guha/rcdk/view/ViewMolecule2D", molecule, as.integer(width),  :
  java.lang.NoSuchMethodError: <init>

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C
[5] LC_TIME=English_United Kingdom.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rcdk_3.4.5   rcdklibs_2.0 rJava_0.9-9

loaded via a namespace (and not attached):
[1] compiler_3.4.3    parallel_3.4.3    fingerprint_3.5.6 tools_3.4.3       iterators_1.0.9
[6] itertools_0.1-3   png_0.1-7


My Java build is (build 1.8.0_151-b12)

**Comment by Tebatu** [comment]
My mistake, I didn't look there. There is no explicit example for `view.molecule.2d`. When I run the example for `view.image.2d` it works fine, but an analogous command for `view.molecule.2d` produces an error as below. I checked the passed object type to make sure it is an `IAtomContainer`.
```
> library(rcdk)
Loading required package: rcdklibs
Loading required package: rJava
> m <- parse.smiles('c1ccccc1C(=O)NC')[[1]]
> typeof(m) # checked the object type
[1] "S4"
> class(m) # checked class
[1] "jobjRef"
attr(,"package")
[1] "rJava"
> dep <- get.depictor(width=200, height=200)
> view.molecule.2d(molecule = m,depictor = dep)
Error in .jnew("org/guha/rcdk/view/ViewMolecule2D", molecule, as.integer(width),  : 
  java.lang.NoSuchMethodError: <init>
```

**Comment by rajarshi** [comment]
Apologies for the delay in replying. Your most recent code, above, works fine for me with the latest `rcdk` code from Hithub. Here's my session info

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rcdk_3.4.5      rcdklibs_2.0    rJava_0.9-9     dplyr_0.5.0     plyr_1.8.4      reshape2_1.4.2  ggplot2_2.2.1   ncgcdb_1.0.1    ROracle_1.2-2   DBI_0.5-1       rsconnect_0.8.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      magrittr_1.5      itertools_0.1-3   munsell_0.4.3     fingerprint_3.5.6 colorspace_1.3-0  R6_2.2.2          stringr_1.2.0     tools_3.3.2       parallel_3.3.2   
[11] grid_3.3.2        gtable_0.2.0      png_0.1-7         iterators_1.0.8   lazyeval_0.2.0    assertthat_0.2.0  digest_0.6.12     tibble_1.2        RJSONIO_1.3-0     bitops_1.0-6     
[21] RCurl_1.95-4.8    stringi_1.1.5     scales_0.4.1     
```
I'm using JDK8

**Comment by stanstrup** [comment]
I get the same error.

```r
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252 LC_NUMERIC=C                   
[5] LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rcdk_3.4.5   rcdklibs_2.0 rJava_0.9-9 

loaded via a namespace (and not attached):
[1] compiler_3.4.1    parallel_3.4.1    fingerprint_3.5.7 tools_3.4.1       yaml_2.1.16       iterators_1.0.9   itertools_0.1-3   png_0.1-7     
```

**Comment by Tebatu** [comment]
@rajarshi, since the function works for you, I redid my Java installation and manually checked that all environmental variables for Java are set correctly. I checked the rJava functionality with other rJava packages and everything works there.
However, I still get an error when running the examples above.

**Comment by rajarshi** [comment]
I just tried it on R 3.4.1 (OS X) with the code from Github and it's working.

I see both of you are on Windows - unfortunately, I don't have access to a Windows machine and haven't actually tested on there. 

Are you able to install from Github on a Windows machine?

**Comment by stanstrup** [comment]
Yes I can install without problems.

**Comment by rajarshi** [comment]
And you get the same problem with the latets Github version?

**Comment by stanstrup** [comment]
Yes that is what I am using.

**Comment by jranke** [comment]
I get this error message 

```
> view.molecule.2d(mols[[1]])
Fehler in .jnew("org/guha/rcdk/view/ViewMolecule2D", molecule, as.integer(width),  :
  java.lang.NoSuchMethodError: <init>
```

when using view.molecule.2d, but view.image.2d works for example when using the code given in the example on the help page.

This is with rcdk from CRAN (3.4.7) on Debian stretch.

**Comment by raalizadeh** [comment]
Hi,
I had a similar problem. It seems like, it requires an active plot session in R before depicting the chemical structure. I wrote a function to save the chemical structure in local derive rather than showing in R viewer or plot. You could give it a try:
############## Here is the function #################
todepict <- function(mol,pathsd){
  result = tryCatch({
    factory <- .jnew("org.openscience.cdk.depict.DepictionGenerator")$withAtomColors()
    factory$withSize(1000,1000)#$getStyle("cow")
    temp1 <- paste0(pathsd)
    result<-factory$depict(mol)$writeTo(temp1)
  }, warning = function(w) {
    result=NULL
  }, error = function(e) {
    result=NULL
  })
  return(result)
}

################### Here is the implementation ########################
mol<-parse.smiles("c1cc(ncc1CN2CCN=C2N[N+](=O)[O-])Cl", kekulise=TRUE)[[1]]
todepict(mol,paste0(getwd(),"/Imidacloprid.png"))

**Comment by gunjanpandey** [comment]
A friend helped me further polish raalizadeh's function so that a single csv file name (column 1) and cannonical smiles (column 2) can be loaded and all structures with their names are saved in the svg format (can be changes to png format or supported other).

#########################################################################
```
chem.str.fig <- function(filename, width = 1000, heigth = 1000){
  
  suppressPackageStartupMessages(require("rJava"))
  suppressPackageStartupMessages(suppressWarnings(require("rcdk")))
  suppressPackageStartupMessages(require("readr"))
  
  todepict <- function(mol, pathsd){
    result = tryCatch({
      factory <- .jnew("org.openscience.cdk.depict.DepictionGenerator")$withAtomColors()
      factory$withSize(width,heigth)#$getStyle("cow")
      temp1 <- paste0(pathsd)
      result<-factory$depict(mol)$writeTo(temp1)
    }, warning = function(w) {
      result=NULL
    }, error = function(e) {
      result=NULL
    })
    return(result)
  }
  
  df <- read_delim(filename, "\t", escape_double = FALSE, 
                   col_names = FALSE, trim_ws = TRUE, col_types = cols())
  for(i in 1:nrow(df)) {
    todepict(parse.smiles(paste0(df$X2[[i]]), kekulise=TRUE)[[1]], #parses structure
             paste0(df$X1[[i]], ".svg", sep="")) #save structure file 
  }
  
  cat(paste0("Job finished check saved structures at: ", getwd()))
} 
```
#########################################################################
implementation 
`chem.str.fig("./names.csv")`

**Comment by apoorvamk19** [comment]
I am getting the same error. @Tebatu and @stanstrup How did you guys solve this issue.
PS: I am using windows as well.

**Comment by garimaloh** [comment]
Please share the solution

**Comment by garimaloh** [comment]
k=view.molecule.2d(m)

**Comment by ricoderks** [comment]
Hi,

I have the same issue. Trying to replicate the example in the vignette:

```
smiles <- c('CCC', 'CCN', 'CCN(C)(C)',
            'c1ccccc1Cc1ccccc1',
            'C1CCC1CC(CN(C)(C))CC(=O)CC')
mols <- parse.smiles(smiles)
view.molecule.2d(mols[[1]])
```

gives the following error:

```
Error in view.molecule.2d(mols[[1]]) : 
  java.lang.NoSuchMethodError: <init>
```

Looking through the issues, I did/found the following:

* get the latests versions from Github.
* I also get the error when using in just R instead of Rstudio, also when starting R with R --vanilla
* I get the same error as in issue #123, when trying to calculate the volume.
* I tried several things from issue #106.
1. What are the class of your mol object?
  
```
.jclass(mols)
.jclass(mols[[1]])
```

I get:

```
> .jclass(mols)
Error in .jcall(o, "Ljava/lang/Class;", "getClass") : 
  RcallMethod: invalid object parameter
> .jclass(mols[[1]])
[1] "org.openscience.cdk.silent.AtomContainer2"
```

2. Class loading: can you load the class (I would expect so)

```
library(rcdk)
J("org/guha/rcdk/view/ViewMolecule2DTable")
```

I get:

```
> J("org/guha/rcdk/view/ViewMolecule2DTable")
[1] "Java-Class-Name: org.guha.rcdk.view.ViewMolecule2DTable"
```

3. Name Shadowing. The error message doesn't make sense unless you are passing the wrong args. Perhaps they are being shadowed by names from another package? Can you try a fresh R session and see how it looks?

I still get the same error when using R from command line or R --vanilla.

I tried the examples on the [rJava](http://www.rforge.net/rJava/) page to see if maybe something is wrong with my installation, but these examples all work.

My java version:

```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)
```

My session info:

```
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_GB.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=nl_NL.UTF-8           LC_COLLATE=en_GB.UTF-8       
 [5] LC_MONETARY=nl_NL.UTF-8       LC_MESSAGES=en_GB.UTF-8      
 [7] LC_PAPER=nl_NL.UTF-8          LC_NAME=nl_NL.UTF-8          
 [9] LC_ADDRESS=nl_NL.UTF-8        LC_TELEPHONE=nl_NL.UTF-8     
[11] LC_MEASUREMENT=nl_NL.UTF-8    LC_IDENTIFICATION=nl_NL.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rcdk_3.6.1   rcdklibs_2.3 rJava_1.0-6 

loaded via a namespace (and not attached):
[1] compiler_4.1.3    parallel_4.1.3    fingerprint_3.5.7 tools_4.1.3      
[5] iterators_1.0.14  itertools_0.1-3   png_0.1-7  
```

Any further tips / comments are highly appreciated!!

Cheers, Rico
