### ISSUE TITLE
wishlist to expose CDK structure generation code in the package

### ISSUE THREAD

**Issue by egonw** [CDK-R/cdkr#64]
See this post on cdk-user: https://sourceforge.net/p/cdk/mailman/message/36278438/

**Comment by rajarshi** [comment]
It'd be straight forward to wrap, preferably using a generator. I didn't think anybody actually used the structure generator code

**Comment by schymane** [comment]
I can back-up Lee/Egon’s interest … there is growing demand for this for sure, it would be great to be able to access it in R. Thanks!

**Comment by zachcp** [comment]
Lee had emailed me directly and I had told him that we can wrap/use anything that is in CDK.  However, what I thought the CDK devs might be able to help with is approaching his problem from within CDK (I am unfamiliar with that module and its usage). Once the logic is understood in java-land,  R wrapping  should be relatively straightforward requiring only the normal fighting a bit against rJava :)

**Comment by rajarshi** [comment]
I assume the discussion is referring to https://cdk.github.io/cdk/2.0/docs/api/org/openscience/cdk/structgen/RandomGenerator.html

Seems straightforward to wrap in an iterator. But it looks like the key thing is an acceptance function. Does anybody know of any examples?

**Comment by egonw** [comment]
ping @steinbeck
