### ISSUE TITLE
test.formula commented out?

### ISSUE THREAD

**Issue by schymane** [CDK-R/cdkr#85]
Is there a reason this is commented out? 
https://github.com/rajarshi/cdkr/blob/master/rcdk/inst/unitTests/runit.rcdk.R#L38 

@sneumann Could be one location to write the get.exact.mass unit test.
base code worksforme if I run off parse.smiles but not the ref to the mol file when I run locally (for obvious reasons, I didn't go digging for the file ...).

```
m <- parse.smiles("C1(C(C(C(C(C1OP(=O)(O)OCC(COC(=O)CCCCCCCNC(=O)CCCCC2SCC3C2NC(=O)N3)OC(=O)CCCCCCC)O)OP(=O)(O)O)OP(=O)(O)O)O)O")[[1]]
do.aromaticity(m)
#note returns FALSE as non-aromatic
do.typing(m)
do.isotopes(m)
convert.implicit.to.explicit(m)
f2 <- get.mol2formula(m)
f2
checkEquals(f2@string, "C35H64N3O21P3S")
#it's easy to add the mass check here then:
checkEquals(get.exact.mass(m),987.2966)
```

**Comment by zachcp** [comment]
this should be uncommented. I may have commented it while bug-fixing and
forgotten to restore it
